env:
  browser: true
  es2021: true
extends:
  - react-app
  - airbnb
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:functional/recommended
  - plugin:functional/disable-type-checked
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - functional
rules:
  react/function-component-definition: [error, { namedComponents: arrow-function }]
  functional/functional-parameters: [error, { enforceParameterCount: false }]
