env:
  browser: true
  es2021: true
extends:
  - react-app
  - airbnb
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:functional/recommended
  - plugin:functional/disable-type-checked
overrides: [
  {
    files: ['src/store/authSlice.js'],
    rules: {
      no-param-reassign: off,
    },
  }
]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - functional
rules:
  object-curly-newline: [error, { ImportDeclaration: { minProperties: 5 } }]
  react/function-component-definition: [error, { namedComponents: arrow-function }]
  react/prop-types: off
  functional/functional-parameters: [error, { enforceParameterCount: false }]
